### ISSUE TITLE
Add documentation version dropdown

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#103]
At some point, to improve upon #71, it would be nice to have a dropdown box for versions. It would also be good to automatically include a banner specifying if the version is not the latest. Example: https://docs.bokeh.org/en/latest/

**Comment by forsyth2** [comment]
https://docs.readthedocs.io/en/stable/versions.html

**Comment by golaz** [comment]
From https://github.com/E3SM-Project/zstash/issues/104; I should have posted the second part here:

Also, I have been looking into how to maintain documentation for multiple version with sphinx. It seems that it might require using an extension. Some options:

- https://sphinxcontrib-versioning.readthedocs.io/en/latest/index.html
- https://holzhaus.github.io/sphinx-multiversion/master/index.html

Read-the-docs can also do documentation for multiple versions. But I don't like the idea of writing documentation so that a commercial service can place ads on them (even if the "ads [are] served ethically", whatever that means).
