### ISSUE TITLE
Move documentation to master

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#104]
GitHub now allows documentation to be built from a branch other than `gh-pages`. If we build the docs off `master`, then developers will only need to submit one pull request for 1) new code, 2) unit tests, and 3) documentation, rather than submitting a separate documentation pull request to `gh-pages`. See https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by golaz** [comment]
There is definitely an advantage to having the documentation source files on master, rather that `gh-pages`. However, I'm concerned about having the html build files on master as well. I think this will greatly "pollute" any PR that also includes documentation changes.

I'm wondering if we could have the best of both worlds with a hybrid approach: documentation source code on master, documentation build html on `gh-pages`. The only downside would be a more complicated build process; but maybe that could be scripted or automated.

Also, I have been looking into how to maintain documentation for multiple version with sphinx. It seems that it might require using an extension. Some options:

- https://sphinxcontrib-versioning.readthedocs.io/en/latest/index.html
- https://holzhaus.github.io/sphinx-multiversion/master/index.html

Read-the-docs can also do documentation for multiple versions. But I don't like the idea of writing documentation so that a commercial service can place ads on them (even if the "ads [are] served ethically", whatever that means).

**Comment by forsyth2** [comment]
From @tomvothecoder: if we stick with GitHub Pages, we will use GitHub Actions to build the docs on `gh-pages` after all of the tests pass. It will only push the built docs to the `gh-pages` branch.
