### ISSUE TITLE
Ability to initiate Globus transfer to remote HPSS archive

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/zstash#121]
A new feature discussed by @golaz at zstash developer meeting. I found this `data_stager` script (https://github.com/lukaszlacinski/e3sm_to_cmip/blob/3a761a35313fa5af70804e0e326ca5d112caf1b8/scripts/README.md) @lukaszlacinski developed for `e3sm_to_cmip`. To achieve initiating Globus transfer of zstash archive to a remote HPSS archive seems can be accommodated by modifying `data_stager`?

**Comment by lukaszlacinski** [comment]
data_stager.py calls the zstash Python module to retrieve zstash archives from an HPSS and extract files from the archives. Then, data_stager.py uses Globus to transfer the extracted files to a remote Globus endpoint. We can add an inverse functionality. data_stager.py will transfer files from a remote Globus endpoint and call zstash to create archives and save them on an HPPS.

**Comment by golaz** [comment]
@chengzhuzhang and @lukaszlacinski : thanks for starting the conversation.

I think data_stager has a lot of pieces that could be reused to enhance the functionality of zstash. 

As a first step, we should focus on allowing users to store output files (during `zstash create` and `zstash update`) to a remote Globus HPSS (actually any Globus endpoint). We can later tackle the reverse problem of extracting from a remote HPSS using zstash.

Here is what I'm envisioning in terms of command line usage:

`zstash create --hpss=nersc:test/ACME_simulations/20170731.F20TR.ne30_ne30.edison  .
`

or alternatively:

`zstash create --hpss=9cd89cfd-6d04-11e5-ba46-22000b92c6ec:test/ACME_simulations/20170731.F20TR.ne30_ne30.edison  .
`

Since we don't have many available remote HPSS, it would be useful to have predefined shortcuts for **NERSC** and possibly **ALCF**. But we should also allow the user to directly specify the Globus endpoint UUID as in the second example above.

In terms of implementation, most of the changes would take place in

https://github.com/E3SM-Project/zstash/blob/master/zstash/hpss.py

We already have two options:

- `hpss=<path>` : local transfer is triggered using hsi commands
- `hpss=none` : files are kept locally

This would add a third option:

- `hpss = <endpoint>:<path>` : for 'put', launch out-going Globus transfer to remote HPSS. For 'get', return error that remote HPSS is not (yet) supported.

To handle the Globus authorization, we could consider adding a '--login' option that the user would first have to run:

`zstash --login <endpoint>`

**Comment by chengzhuzhang** [comment]
Hi @golaz, to allow user to store output files to a remote Globus Endpoint seems a good first step to tackle. I understand like data_stager.py, the new function will relpy on Globus SDK and FAIR Native Login as additional dependency. @lukaszlacinski would you please help with implementing this feature?

**Comment by lukaszlacinski** [comment]
@chengzhuzhang I'm already working on it.

**Comment by chengzhuzhang** [comment]
Awesome. Thank you @lukaszlacinski

**Comment by chengzhuzhang** [comment]
Hey  @lukaszlacinski  we are planning a new zstash release around end of May. It would be nice to have this feature in for the new release. Do you have some updates on this effort? Thank you!

**Comment by chengzhuzhang** [comment]
Hey @lukaszlacinski, i'm just checking back if we have any updates on this. We will have a new zstash release soon. Thanks!

**Comment by lukaszlacinski** [comment]
https://github.com/E3SM-Project/zstash/pull/154
