### ISSUE TITLE
Performance improvement (background, parallel hsi get)

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#17]
To improve performance of `zstash extract`, execute multiple `hsi get` in parallel (with user control flag to set max number) and in the background rather than proceeding purely sequentially as zstash now does:
    
- Retrieve the first relevant tar file from HPSS
- Extract relevant files
- Repeat with the next tar file.

**Comment by zshaheen** [comment]
I'll do this, but this might not have many improvements. I'd assume a user's bandwidth is limited, so the data throughput would remain the same with multiple hsi get commands. However, because we're obtaining multiple large tar archives at the same time, the time to download a single file is increased. To a user, it would seem that the performance of zstash is poor.

In situations like this, [back pressure is applied to the system](https://medium.com/@jayphelps/backpressure-explained-the-flow-of-data-through-software-2350b3e77ce7), which helps mediate this from happening.

---

However, the extraction/checking can be done in parallel. That would be useful.
As we see with `e3sm_diags`, when doing so, the output to the terminal is unreadable.
To alleviate this, we need more control over the multiprocessing. I plan on using a task queue like [Celery](http://www.celeryproject.org), so the output can be managed better.

**Comment by golaz** [comment]
@zshaheen : have you checked whether Celery will run on NERSC (login and data transfer nodes)? Celery requires a broker for message transport (http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html) and I'm wondering whether that could be an issue. We don't want to over-engineer this feature and in the process make it very difficult to install and run zstash.

**Comment by zshaheen** [comment]
@golaz, yes I did think about that. My current implementation will just involve `multiprocessing` and other default synchronization primitive (`theading.Lock`, `threading.Semaphore`, `threading.Condition`, etc). With these, I think I'd be able to make the printing to the terminal orderly.

**Comment by zshaheen** [comment]
The majority of this work was completed in 72b258445f470b1f5c9bb62b9ff1c1cf527ac588. There are some outstanding issues however:
- [ ] When there are MD5 failures with parallel `zstash extract`/`zstash check` (the same code is used to run both of these), the software hangs.
  - Failures are added to a queue (`multiprocessing.Queue`), which is used to propagate the failures that each process encounters to the main process.
  - It's in shared memory, but for some reason, it causes the software to hang.
  - I've tried `multiprocessing.SimpleQueue()`, `multiprocessing.JoinableQueue()` as well to no avail.
  - I also need to add tests that induce an MD5 mismatch error to the test suite as well.
- [ ] When the documentation is done, I'll close this issue.

**Comment by zshaheen** [comment]
The parallel running was working in 0d5151ab753561b8ce76aef040011d2e1959f9cf, the tests were added in 15f21f598c78be48ff2429dea746d711f698eb96. The documentation was updated in 3575901a89526a9c7455db41cccd1a8010cf7601.
