### ISSUE TITLE
Add checksums for tar files

### ISSUE THREAD

**Issue by lukaszlacinski** [E3SM-Project/zstash#62]
In a use case where a user needs to work on a remote machine on different sets of files (unknown upfront) extracted the same zstash tarballs, the user has to extract all files and transfer them to the remote machine. It will be more efficient to transfer the entire zstash tarballs once and extract needed files on the remote machine. Unfortunately, the database does not provide checksums of the zstash tarballs to make sure that the tarballs are transferred from HPSS to a local machine, and then from the local machine to the remote machine without any errors.
It will be helpful to add checksums of the zstash tarballs to the database.

**Comment by golaz** [comment]
When working remotely, the currently recommended approach is to transfer tar files using Globus and then use `zstash --hpss=none` option to extract needed files. We are relying on Globus to make sure the transfer succeeds and on zstash to verify the integrity of the extracted file.

I don't know if there is a way to compute hash of tar files without incurring a large increase in computational cost (from a separate computation of md5 after the tar file is closed). 

Zstash uses a streaming model to compute hash of individual files at the same time as they are added to the tar. This makes the computation of the hash almost free because there is no added IO.

**Comment by golaz** [comment]
@lukaszlacinski: following up on your previous suggestion. I agree that it would be useful to have the md5 checksums of the tar files.

I looked into this some more to see if there was a clever way to compute them  without incurring the cost of reading the files again (which would be quite expensive for large zstash archives).

I now have a proof-of-concept on how to accomplish this (see attached script tar_n_hash.py). The basic idea is to extend the streaming algorithm to simultaneously compute md5 hashes of the individual files and the entire tar file at the same time as the tar file is being created.

[tar_n_hash.py.txt](https://github.com/E3SM-Project/zstash/files/5999241/tar_n_hash.py.txt)

To store the tar files md5, the best option would be an additional database table. We would need to ensure that zstash works regardless of the database schema (old and extended).

I could work with @forsyth2 to implement this new feature. While not overly complicated, this is not a one day task. So I think we need the input from @rljacob and @chengzhuzhang to decide whether that's worth it.
